// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAahRM6swusfpvOlMeWTFKDykaWxW31uxc',
    appId: '1:365815667801:web:645f0ee9caef67eb906548',
    messagingSenderId: '365815667801',
    projectId: 'trisutorpro-815be',
    authDomain: 'trisutorpro-815be.firebaseapp.com',
    storageBucket: 'trisutorpro-815be.firebasestorage.app',
    measurementId: 'G-16PPM986KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ_wZR6B-l0Nks5NlVo9M91bDiZlZc3tI',
    appId: '1:365815667801:android:b127ec4a2a04c4aa906548',
    messagingSenderId: '365815667801',
    projectId: 'trisutorpro-815be',
    storageBucket: 'trisutorpro-815be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFAzkMfSTxuaMk35vJl4rATTuYOz07DQQ',
    appId: '1:365815667801:ios:d49e8d46df0b5923906548',
    messagingSenderId: '365815667801',
    projectId: 'trisutorpro-815be',
    storageBucket: 'trisutorpro-815be.firebasestorage.app',
    iosBundleId: 'com.example.secpanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFAzkMfSTxuaMk35vJl4rATTuYOz07DQQ',
    appId: '1:365815667801:ios:d49e8d46df0b5923906548',
    messagingSenderId: '365815667801',
    projectId: 'trisutorpro-815be',
    storageBucket: 'trisutorpro-815be.firebasestorage.app',
    iosBundleId: 'com.example.secpanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAahRM6swusfpvOlMeWTFKDykaWxW31uxc',
    appId: '1:365815667801:web:721697da3ebe75ef906548',
    messagingSenderId: '365815667801',
    projectId: 'trisutorpro-815be',
    authDomain: 'trisutorpro-815be.firebaseapp.com',
    storageBucket: 'trisutorpro-815be.firebasestorage.app',
    measurementId: 'G-NYMYJGH5XV',
  );
}
